vich_uploader:
    db_driver: orm

    mappings:
        utilisateur:
            uri_prefix: /images/utilisateur
            upload_destination: '%kernel.project_dir%/public/images/utilisateur'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
