vich_uploader:
    db_driver: orm

    mappings:
        colis_image:
            uri_prefix: /uploads/colis
            upload_destination: '%kernel.project_dir%/public/uploads/colis'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        users_image:
                uri_prefix: /uploads/user
                upload_destination: '%kernel.project_dir%/public/uploads/users'
                namer: Vich\UploaderBundle\Naming\UniqidNamer

        article_image:
                uri_prefix: /uploads/article
                upload_destination: '%kernel.project_dir%/public/uploads/article'
                namer: Vich\UploaderBundle\Naming\UniqidNamer